"""empty message

Revision ID: cbd9cabc6f4d
Revises: 
Create Date: 2022-05-22 17:44:21.960992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd9cabc6f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numMaquinas', sa.Integer(), nullable=False),
    sa.Column('numOperacoes', sa.Integer(), nullable=False),
    sa.Column('numTrabalhos', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simul_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simul_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simul_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simul_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simul_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['simul_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('machine')
    op.drop_table('job')
    op.drop_table('todo')
    op.drop_table('simulation')
    # ### end Alembic commands ###
